sudo: false
language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before-install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
script:
  - yarn test-ci
