# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn --cache-min 999999999    
    yarn
    yarn run build
  displayName: 'yarn run build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: 'dist'